<?php

return [
    'cookie_prefix' => 'crowdsourcing_app_',
    'display_floating_button' => true,
    'hide_floating_button_on_mobile' => true,
    'use_separate_page' => false,
    'cookies' => [
        'strictly_necessary' => [
            [
                'name' => 'crowdsourcing_app_cookies_consent',
                'description' => 'cookies_consent::messages.cookie_cookies_consent_description',
                'duration' => 'cookies_consent::messages.years',
                'duration_count' => 1,
                'policy_external_link' => null,
            ],
            [
                'name' => 'XSRF-TOKEN',
                'description' => 'cookies_consent::messages.cookie_xsrf_token_description',
                'duration' => 'cookies_consent::messages.hours',
                'duration_count' => 2,
                'policy_external_link' => null,
            ],
            [
                'name' => 'laravel_session',
                'description' => 'cookies_consent::messages.cookie_laravel_session_description',
                'duration' => 'cookies_consent::messages.hours',
                'duration_count' => 2,
                'policy_external_link' => null,
            ],
        ],
        'targeting' => [
            [
                'name' => '_ga',
                'description' => 'cookies.google_analytics._ga_description',
                'duration' => 'cookies_consent::messages.years',
                'duration_count' => 2,
                'policy_external_link' => 'https://policies.google.com/privacy?hl=en-US',
            ],
            [
                'name' => '_gid',
                'description' => 'cookies.google_analytics._gid_description',
                'duration' => 'cookies_consent::messages.days',
                'duration_count' => 1,
                'policy_external_link' => 'https://policies.google.com/privacy?hl=en-US',
            ],
            [
                'name' => '_gat',
                'description' => 'cookies.google_analytics._gat_description',
                'duration' => 'cookies_consent::messages.minutes',
                'duration_count' => 1,
                'policy_external_link' => 'https://policies.google.com/privacy?hl=en-US',
            ],
            [
                'name' => 'bcookie',
                'description' => 'cookies.linkedin.bcookie_description',
                'duration' => 'cookies_consent::messages.years',
                'duration_count' => 2,
                'policy_external_link' => 'https://www.linkedin.com/legal/privacy-policy',
            ],
            [
                'name' => '_fbp',
                'description' => 'cookies.facebook._fbp_description',
                'duration' => 'cookies_consent::messages.months',
                'duration_count' => 3,
                'policy_external_link' => 'https://www.facebook.com/policy/cookies/',
            ],
            [
                'name' => '_gcl_au',
                'description' => 'cookies.google_ads._gcl_au_description',
                'duration' => 'cookies_consent::messages.months',
                'duration_count' => 2,
                'policy_external_link' => 'https://policies.google.com/privacy?hl=en-US',
            ],
            [
                'name' => 'guest_id',
                'description' => 'cookies.twitter.guest_id_description',
                'duration' => 'cookies_consent::messages.years',
                'duration_count' => 2,
                'policy_external_link' => 'https://twitter.com/en/privacy',
            ],
            [
                'name' => 'guest_id_ads',
                'description' => 'cookies.twitter.guest_id_ads_description',
                'duration' => 'cookies_consent::messages.years',
                'duration_count' => 2,
                'policy_external_link' => 'https://twitter.com/en/privacy',
            ],
            [
                'name' => 'guest_id_marketing',
                'description' => 'cookies.twitter.guest_id_marketing_description',
                'duration' => 'cookies_consent::messages.years',
                'duration_count' => 2,
                'policy_external_link' => 'https://twitter.com/en/privacy',
            ],
            [
                'name' => 'li_gc',
                'description' => 'cookies.linkedin.li_gc_description',
                'duration' => 'cookies_consent::messages.years',
                'duration_count' => 2,
                'policy_external_link' => 'https://www.linkedin.com/legal/privacy-policy',
            ],
            [
                'name' => 'lidc',
                'description' => 'cookies.linkedin.lidc_description',
                'duration' => 'cookies_consent::messages.day',
                'duration_count' => 1,
                'policy_external_link' => 'https://www.linkedin.com/legal/privacy-policy',
            ],
            [
                'name' => 'muc_ads',
                'description' => 'cookies.twitter.muc_ads_description',
                'duration' => 'cookies_consent::messages.years',
                'duration_count' => 2,
                'policy_external_link' => 'https://twitter.com/en/privacy',
            ],
            [
                'name' => 'personalization_id',
                'description' => 'cookies.twitter.personalization_id_description',
                'duration' => 'cookies_consent::messages.years',
                'duration_count' => 2,
                'policy_external_link' => 'https://twitter.com/en/privacy',
            ],
        ],
    ],
    'enabled' => [
        'strictly_necessary',
    ],
    'required' => ['strictly_necessary'],
    'cookie_lifetime' => 365,
];
