name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - name: Run composer install
        run: composer install -n --prefer-dist
      - name: Copy .env
        run: cp .env.testing.example .env.testing && cp .env.testing .env
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Migrate
        run: php artisan migrate --database=sqlite_testing
      - name: Seed
        run: php artisan db:seed --database=sqlite_testing
      - name: Cache
        run: php artisan config:cache --env=testing
      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        run: php artisan test