name: "Run Laravel Tests"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Run composer install
        run: composer install -n --prefer-dist --no-ansi --no-progress --no-suggest --no-interaction --no-scripts

      - name: Install npm dependencies
        run: npm install

      - name: Build assets with Vite
        run: npm run build

      - name: Copy .env
        run: cp .env.testing.example .env.testing && cp .env.testing .env

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create storage directories
        run: |
          mkdir -p storage/app
          mkdir -p storage/app/public/uploads/user_profile_img

      - name: Storage Link
        run: php artisan storage:link --env=testing

      - name: Cache
        run: php artisan config:cache --env=testing

      - name: Run the migrations in the testing environment
        run: php artisan migrate --env=testing --database=sqlite_testing

      - name: Run the seeders in the testing environment
        run: php artisan db:seed --env=testing --database=sqlite_testing

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: php artisan test --env=testing