name: linter

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

permissions:
    contents: write

jobs:
    quality:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

            - name: Setup PHP
              uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2 # NOSONAR - This action is widely used and trusted
              with:
                  php-version: '8.4'

            - name: Setup Node.js
              uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
              with:
                  node-version-file: '.nvmrc'

            - name: Copy Environment File
              run: cp .env.testing .env

            - name: Upgrade npm
              run: npm install -g npm@11.16.0 --ignore-scripts

            - name: Install Dependencies
              run: |
                  composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
                  npm ci --ignore-scripts

            - name: Run Pint
              run: vendor/bin/pint --test -v

            - name: Lint Frontend
              run: npm run lint
